from typing import Any

SurfaceType: Any
OptMode: Any

class SurfaceOptimizationEnv:
    def __init__(
        self,
        dim: int = ...,
        surface_type: Any = ...,
        mode: Any = ...,
        step_size: float = ...,
        bounds_low: float = ...,
        bounds_high: float = ...,
        convergence_tolerance: float = ...,
        max_steps: int = ...,
        seed: int = ...,
    ) -> None: ...
    def reset(self) -> list[float]: ...
    def step(self, action: int) -> tuple[list[float], float, bool, float]: ...
    def step_continuous(self, action: list[float]) -> tuple[list[float], float, bool, float]: ...
    @property
    def dim(self) -> int: ...
    @property
    def action_size(self) -> int: ...
    @property
    def optimal_value(self) -> float: ...
    @property
    def optimal_position(self) -> list[float]: ...
    @property
    def position(self) -> list[float]: ...
    @property
    def function_name(self) -> str: ...
    @property
    def surface_type(self) -> Any: ...
    @property
    def mode(self) -> Any: ...
    @property
    def step_size(self) -> float: ...
    @property
    def max_steps(self) -> int: ...
    @property
    def bounds(self) -> tuple[float, float]: ...
    def set_custom_coefficients(self, coeffs: list[float]) -> None: ...
    def set_custom_optimal(self, position: list[float], value: float) -> None: ...
